sudo: false
language: php
php:
    - 7.0
    - 7.1
services:
    - postgresql
before_install:
    - psql -c 'create database travis_ci_test;' -U postgres
    - php -r "file_exists('.env') || copy('.env.travis', '.env');"
install:
    - composer install
    - php artisan key:generate
script:
    - php artisan migrate
    - php artisan db:seed
    - php artisan vendor:publish --force
    - php vendor/bin/phpunit --coverage-clover=./storage/logs/coverage.xml
after_script:
    - php vendor/bin/codacycoverage clover ./storage/logs/coverage.xml
