sudo: false

language: php

php:
    - 7.0
    - 7.1

env:
    - DB=mysql
    - DB=postgres

services:
    - postgresql
    - mysql

before_install:
    - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'create database plus;' -U postgres"
    - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE IF NOT EXISTS plus;'"
    - sh -c "php ./.travis.php "$DB""
    - php -r "file_exists('.env') || copy('.env.travis', '.env');"

install:
    - composer install
    - php artisan key:generate

script:
    - php artisan migrate
    - php artisan db:seed
    - php artisan vendor:publish --force
    - php vendor/bin/phpunit --coverage-clover=./storage/logs/coverage.xml

after_script:
    - php vendor/bin/codacycoverage clover ./storage/logs/coverage.xml
