language:
    - php
    - node_js

php:
    - 7.0
    - 7.1

node_js:
    - 6

services:
    - mysql

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS thinksns_plus;'
    - php -r "file_exists('.env') || copy('.env.example', '.env');"

install:
    - composer install
    - php artisan key:generate
    - yarn install

script:
    - php artisan migrate
    - php artisan db:seed
    - php vendor/bin/phpunit --coverage-clover=./storage/logs/coverage.xml
    - yarn lint
    - yarn build
    - yarn dist

after_script:
    - php vendor/bin/codacycoverage clover ./storage/logs/coverage.xml
