version: 2
jobs:
    build:
        working_directory: ~/plus
        docker:
            - image: circleci/node:6
        steps:
            - checkout
            - run:
                name: Install Yarn
                command: curl -o- -L https://yarnpkg.com/install.sh | bash
            - run:
                name: Run yarn install
                command: yarn install

    test:
        working_directory: ~/plus
        docker:
            - image: circleci/node:6
        steps:
            - run:
                name: dist
                command: yarn dist
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test:
                requires:
                    - build
                filters:
                    branches:
                        only: master
